
server:
  port: 8083
spring:
  application:
    name: BILLING-SERVICE
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:h2:mem:billing-db
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

